### PR TITLE
Fixes for librdkit-dev and rdkit-postgresql

### LINKED ISSUE #165: rdkit-postgresql is broken on OSX
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The symbolic link here is not being included in the installed package: https://github.com/conda-forge/rdkit-feedstock/blob/5377ec318d340a2ba067b24494d8c48a3ced45e9/recipe/install.sh#L36

```psql
test=# create extension rdkit;
ERROR:  could not access file "$libdir/rdkit": No such file or directory
```

Manually adding the link fixes the issue:

```shell
cd $(pg_config --pkglibdir)
ln -s rdkit.so rdkit.dylib
```

I'm testing alternatives to the symbolic link in install.sh, but I wonder if @jaimergp has ideas about why this isn't working as-is?

### Installed packages

```shell
# packages in environment at /Users/skearnes/mambaforge/envs/ord:
#
# Name                    Version                   Build  Channel
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
appnope                   0.1.4                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asn1crypto                1.5.1                    pypi_0    pypi
astroid                   3.2.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
black                     24.4.2                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
bzip2                     1.0.8                h99b78c6_7    conda-forge
ca-certificates           2024.7.4             hf0a4a13_0    conda-forge
cairo                     1.18.0               hb4a6bf7_3    conda-forge
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
coverage                  7.6.0                    pypi_0    pypi
cryptography              43.0.0                   pypi_0    pypi
debugpy                   1.8.2                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
execnet                   2.1.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
expat                     2.6.2                hebf3989_0    conda-forge
fastapi                   0.111.1                  pypi_0    pypi
fastapi-cli               0.0.4                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               hadb7bae_2    conda-forge
gunicorn                  22.0.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.7                      pypi_0    pypi
immutabledict             4.2.0                    pypi_0    pypi
importlab                 0.8.1                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.26.0                   pypi_0    pypi
ipywidgets                8.1.3                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
isort                     5.13.2                   pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
json5                     0.9.25                   pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.6.2                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.2                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.2.4                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.3                   pypi_0    pypi
jupyterlab-widgets        3.0.11                   pypi_0    pypi
krb5                      1.21.3               h237132a_0    conda-forge
libboost                  1.84.0               hf763ba5_4    conda-forge
libcst                    1.4.0                    pypi_0    pypi
libcxx                    18.1.8               h167917d_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libglib                   2.80.3               h59d46d9_1    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libintl                   0.22.5               h8fbad5d_2    conda-forge
libpng                    1.6.43               h091b4b1_0    conda-forge
libpq                     16.3                 h7afe498_0    conda-forge
librdkit                  2024.03.5            h54a62e4_1    conda-forge
libsqlite                 3.46.0               hfb93653_0    conda-forge
libxml2                   2.12.7               h01dff8b_4    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
msgspec                   0.18.6                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  hb89a1cb_0    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
notebook                  7.2.1                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   3.3.1                hfb2fe0b_2    conda-forge
ord-interface             0.0.0                    pypi_0    pypi
ord-schema                0.3.88                   pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pcre2                     10.44                h297a79d_0    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pg8000                    1.31.2                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               hebf3989_0    conda-forge
platformdirs              4.2.2                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
postgresql                16.3                 hdfa2ec6_0    conda-forge
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
protobuf                  4.22.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
psycopg                   3.2.1                    pypi_0    pypi
psycopg-binary            3.2.1                    pypi_0    pypi
psycopg-pool              3.2.2                    pypi_0    pypi
psycopg2-binary           2.9.9                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pycnite                   2024.7.9                 pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydot                     3.0.1                    pypi_0    pypi
pygithub                  2.3.0                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
pylint                    3.2.6                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pytest                    8.3.1                    pypi_0    pypi
pytest-cov                5.0.0                    pypi_0    pypi
pytest-xdist              3.6.1                    pypi_0    pypi
python                    3.11.9          h932a869_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytype                    2024.4.11                pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.0.3                   pypi_0    pypi
qtconsole                 5.5.2                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
rdkit                     2024.3.3                 pypi_0    pypi
rdkit-postgresql          2024.03.5            h69bff49_1    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.19.1                   pypi_0    pypi
scramp                    1.4.5                    pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlalchemy                2.0.31                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
starlette                 0.37.2                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
testing-common-database   2.0.3                    pypi_0    pypi
testing-postgresql        1.3.0                    pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tk                        8.6.13               h5083fa2_1    conda-forge
tokenize-rt               5.2.0                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomlkit                   0.13.0                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
treon                     0.1.4                    pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzcode                    2024a                h93a5062_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
uvicorn                   0.30.3                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
watchfiles                0.22.0                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.6.0                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.11                   pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.3.1                hfb2fe0b_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
active environment : ord
    active env location : /Users/skearnes/mambaforge/envs/ord
            shell level : 2
       user config file : /Users/skearnes/.condarc
 populated config files : /Users/skearnes/mambaforge/.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.3.0=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Users/skearnes/mambaforge  (writable)
      conda av data dir : /Users/skearnes/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/skearnes/mambaforge/pkgs
                          /Users/skearnes/.conda/pkgs
       envs directories : /Users/skearnes/mambaforge/envs
                          /Users/skearnes/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by skearnes**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #165 

* Updates `rdkit-postgresql` to avoid a symbolic link on OSX (rename to dylib instead)
* Adds `rdkit-dev` as an alias for librdkit-dev + rdkit (for backward compatibility with the old `rdkit-dev` package; see https://github.com/conda-forge/rdkit-feedstock/issues/167#issuecomment-2250376432)

### CODE REVIEW

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Comment by skearnes** [comment]
@jaimergp the reason renaming [didn't work before](https://github.com/conda-forge/rdkit-feedstock/pull/158#discussion_r1669135047) is because I was trying to do it before the install 🤦

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Comment by skearnes** [comment]
@greglandrum @jaimergp what's the convention now that I'm an owner? I assume I should still wait for a review?

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
