### PR TITLE
Bump to 2022.09.1 release

### PR DESCRIPTION
**Pull request by greglandrum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by greglandrum** [comment]
@conda-forge-admin, please rerender

**Comment by greglandrum** [comment]
@jaimergp I don't see any particular reason why the py38 osx_arm64 build should fail when the others all pass, and the failure itself (which seems be caused by conda seg faulting) doesn't particularly make sense to me.
Can you make azure devops rerun that one failed build to see if that helps?

**Review by pstjohn — APPROVED** [review]

**Comment by greglandrum** [comment]
Hi, could someone please merge this so that the new RDKit version is available from conda-forge?

Thanks!
-greg

**Comment by greglandrum** [comment]
Thanks @mcs07 !

**Pull request merged**
