### PR TITLE
Windows builds and version format change

### LINKED ISSUE #1: Support py3k on windows
Py3k builds on windows are currently disabled because of what appears to be a boost linking problem:

```
[ 30%] Linking CXX shared module ..\..\..\rdkit\Avalon\pyAvalonTools.pyd
   Creating library pyAvalonTools.lib and object pyAvalonTools.exp
pyAvalonTools.cpp.obj : error LNK2019: unresolved external symbol "class ExplicitBitVect const
volatile * __cdecl boost::get_pointer<class ExplicitBitVect const volatile >(class ExplicitBitVect const
volatile *)" (??$get_pointer@$$CDVExplicitBitVect@@@boost@@YAPDVExplicitBitVect@@PDV1@@Z) referenced
 in function "public: static struct _object * __cdecl boost::python::objects::make_instance_impl<class
ExplicitBitVect,struct boost::python::objects::pointer_holder<class std::auto_ptr<class
ExplicitBitVect>,class ExplicitBitVect>,struct boost::python::objects::make_ptr_instance<class
ExplicitBitVect,struct boost::python::objects::pointer_holder<class std::auto_ptr<class
ExplicitBitVect>,class ExplicitBitVect> > >::execute<class std::auto_ptr<class ExplicitBitVect> 
(class std::auto_ptr<class ExplicitBitVect> &)" (??$execute@V
$auto_ptr@VExplicitBitVect@@@std@@@?$make_instance_impl@VExplicitBitVect@@U
$pointer_holder@V?$
```

(turning off AvalonTools didn't solve the problem either unfortunately.)

### LINKED ISSUE #10: version number
The version number does not follow and standard, can we change this to be in sync with the rest and also with the rdkit conda channel?

### PR DESCRIPTION
**Pull request by mcs07**
- Use semantic version format that conda understands - fixes #10.
- Enable windows builds - fixes #1. A patch is needed to build with VS2015 (python 3).
- Add pycairo as run requirement. While strictly an optional dependency, it is basically a requirement for adequate depiction outputs.
- Add myself as maintainer.

### CODE REVIEW

**Comment by mcs07** [comment]
@pstjohn Would you able to review this? Sorry there are multiple changes bundled in a single PR.

**Comment by pstjohn** [comment]
Yeah this looks great, thanks for the help!
We might see if @greglandrum would want to merge the patch upstream

**Comment by greglandrum** [comment]
@mcs07 : that looks like a really useful patch. I don't think I'd have an objection to integrating it upstream in the RDKit.

**Comment by mcs07** [comment]
We did discuss it a long while ago - see https://github.com/rdkit/rdkit/pull/1152. I think it seemed a bit excessive to add it solely to support VS2015 Update 3, but that's what we are stuck with on Appveyor...

**Comment by greglandrum** [comment]
Ok, now I remember that. Still there are some people who are stuck with VS2015 and can't go backward from update 3 to update 2, so it might be worth having.
Re: appveyor
you can switch to VS2017 there, but I guess that's not right for a "real" python extension build.

**Pull request merged**
