### PR TITLE
Update to release 2020.03.1

### PR DESCRIPTION
**Pull request by greglandrum**
Switches to using the newly released RDKit v2020.03.1

### CODE REVIEW

**Comment by mcs07** [comment]
Weird CI failure on the Windows builds. I'll fix the license complaint from the linter and see if it succeeds when it re-runs.

**Comment by mcs07** [comment]
Oh, not sure I can push to your branch. It should be:

```
license: BSD-3-Clause
license_family: BSD
```

**Comment by greglandrum** [comment]
@mcs07 : I updated the license, but it looks like the windows builds failed with the same odd error. This doesn't seem like it was a result of anything I changed, but I created #45 just to be sure.

**Comment by pstjohn** [comment]
lets see if rerendering in #45 fixes it

**Comment by greglandrum** [comment]
@conda-forge-admin, please rerender

**Comment by pstjohn** [comment]
LGTM?

**Pull request merged**
