### PR TITLE
New build to fix broken 2021.09.4 package

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
See https://github.com/conda-forge/rdkit-feedstock/issues/93 and https://github.com/rdkit/rdkit/issues/4987 for details.

**Comment by hadim** [comment]
@conda-forge/rdkit should we pin `boost` here?

**Comment by hadim** [comment]
It seems like the rebuild need this https://github.com/rdkit/rdkit/pull/4885 to work but it's not available for 2021.09.4.

**Comment by mcs07** [comment]
We should be able to add https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/4885.patch as a patch within the recipe to fix this. Let me know @hadim if you'd like me to have a go at this on your PR here, or if you're OK to handle it.

Additionally, based on https://github.com/conda-forge/boost-cpp-feedstock/issues/114 we may also need to add `zlib` as a host requirement?

**Comment by mcs07** [comment]
Oh and we may soon be getting a new boost package anyway that fixes the problem? https://github.com/conda-forge/boost-cpp-feedstock/pull/115

**Comment by hadim** [comment]
> Oh and we may soon be getting a new boost package anyway that fixes the problem? [conda-forge/boost-cpp-feedstock#115](https://github.com/conda-forge/boost-cpp-feedstock/pull/115)

Indeed let's wait for that PR to be merged as it might fix the rdkit package.

**Comment by hadim** [comment]
I confirm boost-cpp 1.74 build 7 (from https://github.com/conda-forge/boost-cpp-feedstock/pull/115) fixes the issue for me so likely for the others too. Closing here.

**Pull request closed without merging**
