### PR TITLE
running mac builds for py27 and py35

### LINKED ISSUE #2: Support py35 and py27 on mac
Currently disabled because the builds time out on Travis. Would probably have to wait for something like conda-forge/conda-smithy#526 it that would work

### PR DESCRIPTION
**Pull request by pstjohn**
Fixes #2

### CODE REVIEW

**Comment by pstjohn** [comment]
Ugh, now windows x86 builds are failing. I think we should turn them off entirely until we have all the python versions working. Would that be ok @greglandrum?

**Comment by greglandrum** [comment]
@pstjohn : I suppose so. It does look like this particular failure is on the 32bit build, which I think is fine to skip in any case. I haven't done 32bit builds for the RDKit python stuff in quite a while and there haven't been any complaints.

I can try to spend some time looking at the windows builds over the holidays. What's the easiest way for me to do this and have the appropriate CI builds run?

**Comment by pstjohn** [comment]
Huh, sourceforge is down, causing the builds to fail. Although it makes me wonder if we'd have better luck if we could provide those packages separately (i.e,. conda install inchi)? or if we're allowed to just include the source files as part of the recipe.

In terms of how to debug the windows builds, the best way would be for you to
* fork this repository (`rdkit-feedstock`, the button's on the top right of the screen),
* clone the forked repository, `git clone https://github.com/greglandrum/rdkit-feedstock.git`
* checkout a new branch, i.e., `git checkout -b windows`
* make some changes to the meta.yaml / bld.bat files. The line (`skip: true  # [win]` is currently what disables the builds, so remove that)
* push those changes to your forked repo (`git push origin windows`)
* On the website, you should see a button to open up a pull request to this repo -- that will trigger the CI builds to run.

**Comment by greglandrum** [comment]
for what it's worth: I have managed to confirm that least the `master` version of this repo works for me on the Mac (High Sierra) using python 3.6. That's awesome. :-)

Something that may help with the timeouts is to add `-D RDK_BUILD_CPP_TESTS=OFF` to the cmake flags. The C++ tests are not run as part of this recipe and they do take a non-trivial amount of time to build.

**Comment by mcs07** [comment]
I had the same idea about a separate InChI package to save a few minutes on the build time. The recipe is here: https://github.com/mcs07/conda-recipes/tree/master/recipes/inchi

I can't remember if I ever got it working as a dependency of the rdkit recipe. Could be worth making a conda-forge feedstock for it?

**Comment by greglandrum** [comment]
Yeah, conda 4.4 remains a massive challenge. The linux and windows builds currently hosted in the rdkit conda channel should work with newer versions of conda, but I haven't been able to get a Mac build to work at all with "new conda".
If I do everything with conda-forge everything works great, but the moment I start using things from the "standard" conda it fails. It's "a bit" frustrating.

**Pull request merged**
