### PR TITLE
update to new release

### PR DESCRIPTION
**Pull request by greglandrum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mcs07** [comment]
Same timeouts that were seen in #79? I'm not sure why these are taking >6 hours now - looking at the last release they were all 3-4 hours?

**Comment by jaimergp** [comment]
We might need to cross-compile for PPC, but it'd be better to fix the vendored dependencies problem first.

**Comment by mcs07** [comment]
I agree that unvendoring would be good, but might take quite a bit of effort. Some should be mostly straightforward, like InChI, coordgen and maeparser, but I believe that others like RapidJSON and AvalonTools will actually require changes to the RDKit CMake configuration to allow for an externally provided library.

It would be really nice to get the 2019.09.1 release out as soon as possible... how does everyone feel about merging this PR now and then working on fixing the PPC packages afterwards?

**Comment by greglandrum** [comment]
> Agreed that it's ok to release the new RDKit like this, provided that unvendoring happens in a new build later. PPC can be disabled until then.

Thanks! for what it's worth, the usage of the linux_ppc stuff does seem to be pretty low. Check slides 4 and 5 here:
https://github.com/rdkit/UGM_2021/blob/main/Presentations/Landrum_StateOfTheToolkit.pdf

**Comment by jaimergp** [comment]
I guess we can enable `freesasa` here while we are at it :)

**Comment by greglandrum** [comment]
I just noticed that I messed up the release numbering in the main RDKit `CMakeLists.txt` file. <sigh>
I'm going to do a 2021.09.2 release with that fixed after I've had a chance to verify that I actually have it right now.

**Comment by mcs07** [comment]
We could maybe catch this in future by adding something like this to the conda recipe:

```yaml
tests:
  commands:
    - python -c "import sys; import rdkit; sys.exit(0) if rdkit.__version__ == '{{ version }}' else sys.exit(1)"
```

**Pull request merged**
