### PR TITLE
bump to 2020.09.1 rdkit release

### PR DESCRIPTION
**Pull request by greglandrum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by greglandrum** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
All Windows builds are failing due to:

```
CMake Error at Code/GraphMol/MolDraw2D/CMakeLists.txt:42 (target_link_libraries):
  Cannot specify link libraries for target "MolDraw2D_static" which is not
  built by this project.
```

**Comment by mcs07** [comment]
I think we can "solve" this by adding `-D RDK_INSTALL_STATIC_LIBS=OFF ^` to bld.bat. It already has `-D RDK_INSTALL_DEV_COMPONENT=OFF ^` (which I though did a similar thing?). Although this probably indicates something is not quite right in the CMake logic in how these two options interact.

**Comment by greglandrum** [comment]
Yeah, I think it's time to spend some quality time playing with build options and getting this straightened out. In the meantime I will try the change @mcs07 suggests.

**Comment by jaimergp** [comment]
Looks like that change does the trick for now!

**Review by jaimergp — APPROVED** [review]

**Review by mcs07 — APPROVED** [review]

**Comment by mcs07** [comment]
Thanks for this Greg. Not sure why the bots didn't trigger this PR automatically.

**Pull request merged**
