### PR TITLE
Switch to RDKit v2018.09.2

### PR DESCRIPTION
**Pull request by greglandrum**
bump to the next RDKit release.

Q: I also bumped the build number. Not sure if that's right

### CODE REVIEW

**Comment by greglandrum** [comment]
@mcs07 @pstjohn : If I didn't get this right, please let me know

**Comment by mcs07** [comment]
Hi Greg, there is a bot that has already opened a PR at #25. What you have done here looks all fine to me, except it seems the convention is to revert the build number back to zero for each new version. The bot has also done a 're-render' using the conda-smithy tool that generates these feedstock repositories, so that has also updated a lot of the CI scripts to their latest versions.

**Comment by greglandrum** [comment]
Ah, awesome. so I didn't need to do this at all and can close the PR, right?

**Comment by mcs07** [comment]
Yep, feel free to close.

**Comment by greglandrum** [comment]
Thanks Matt

**Pull request closed without merging**
