### PR TITLE
Enable ppc64le / aarch64

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
We will need to add `pycairo` to the migration. CF only has Linux / Win packages, but defaults does provide `ppc64le`. We shouldn't take it from there though.

**Comment by jaimergp** [comment]
`ppc64le` [fails ](https://travis-ci.com/github/conda-forge/rdkit-feedstock/jobs/357299427#L759) with:

```
[  1%] Building CXX object Code/RDStreams/CMakeFiles/RDStreams.dir/streams.cpp.o
powerpc64le-conda_cos7-linux-gnu-c++: error: unrecognized command line option '-mpopcnt'; did you mean '-mpopcntb'?
make[2]: *** [Code/RDStreams/CMakeFiles/RDStreams.dir/build.make:80: Code/RDStreams/CMakeFiles/RDStreams.dir/streams.cpp.o] Error 1
```

However I don't see this option in `build.sh` and I don't think the compilers include this unrecognized flag, so I guess it's part of `rdkit`'s CMake configuration?

**Comment by jaimergp** [comment]
Local tests for `ppc64le` and Python 3.7:  [build.log.zip](https://github.com/conda-forge/rdkit-feedstock/files/4899060/build.log.zip)

Two errors:

```
99% tests passed, 2 tests failed out of 180

Total Test time (real) = 538.96 sec

The following tests FAILED:
	 91 - test3D (Child aborted)
	 96 - pyMolDescriptors (Failed)
```

**Comment by jaimergp** [comment]
Ok, this should work on the next release. There's a subtle issue for `ppc64le` that will be addressed in the next release. See https://github.com/rdkit/rdkit/pull/3285 for details.

I suggest waiting until then to update this PR and merge without patches.

@mcs07, @pstjohn, would you mind if I added myself as a maintainer?

**Comment by mcs07** [comment]
Go for it! Thanks for all your work on this PR.

**Comment by jaimergp** [comment]
HTTP error in ppc64le, retrying...

**Comment by jaimergp** [comment]
There's a new error with CMake I am investigating.

**Comment by jaimergp** [comment]
Let's see if it was a weird conda solver issue.

**Comment by jaimergp** [comment]
Well, that did it! Ready for review @mcs07!

**Pull request merged**
