### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by greglandrum**
I'm not sure what triggers the bot that normally does this, but since it's been a while and the new release hasn't showed up I figured I would do it by hand.

Checklist
* [x ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by greglandrum** [comment]
@conda-forge-admin, please rerender

**Comment by greglandrum** [comment]
The single CI build failure doesn't look real. Could one of the maintainers please rerun just that failing job in azure pipelines?

**Comment by mcs07** [comment]
Restarted the single OSX failure on Azure. The Drone CI failure looks like a weird issue with the CI tools also, but not sure how to restart that without triggering the whole lot again...

**Comment by mcs07** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
