### PR TITLE
Fix Windows DLL loading issue

### LINKED ISSUE #168: DLL load failed while importing rdBase on Windows with RDKit 2024.03.5
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/rdkit/rdkit/issues/7679

### Installed packages

```shell
# packages in environment at C:\Users\runneradmin\miniconda3\envs\spyrmsd:
#
# Name                    Version                   Build  Channel
black                     24.4.2          py310h5588dad_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h32b962e_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h8d17308_0    conda-forge
chardet                   5.2.0           py310h5588dad_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
codecov                   2.1.13             pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py310h232114e_0    conda-forge
coverage                  7.6.0           py310ha8f682b_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
flake8                    7.1.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py310ha8f682b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
greenlet                  3.0.3           py310h00ffb61_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py310hb4db72f_1    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_0    conda-forge
pebble                    5.0.7              pyhd8ed1ab_0    conda-forge
pillow                    10.4.0          py310h3e38d90_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
psutil                    6.0.0           py310ha8f682b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pycairo                   1.26.1          py310hb6096a9_0    conda-forge
pycodestyle               2.12.0             pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytest                    8.3.2              pyhd8ed1ab_0    conda-forge
pytest-benchmark          4.0.0              pyhd8ed1ab_0    conda-forge
pytest-cov                5.0.0              pyhd8ed1ab_0    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               hc790b64_5    conda-forge
rdkit                     2024.03.5       py310h142e3df_2    conda-forge
reportlab                 4.2.2           py310ha8f682b_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rustworkx                 0.15.1          py310hddca29c_0    conda-forge
scipy                     1.14.0          py310h46043a1_1    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyrmsd                   0.9.0.dev0               pypi_0    pypi
sqlalchemy                2.0.31          py310ha8f682b_0    conda-forge
tbb                       2021.12.0            hc790b64_3    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.1.0          py310h8d17308_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zstandard                 0.23.0          py310he5e10e1_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

### Environment info

```shell
mamba version : 1.5.8
     active environment : spyrmsd
    active env location : C:\Users\runneradmin\miniconda3\envs\spyrmsd
            shell level : 1
       user config file : C:\Users\runneradmin\.condarc
 populated config files : C:\Users\runneradmin\miniconda3\.condarc
                          C:\Users\runneradmin\.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64_v3
                          __conda=24.3.0=0
                          __win=0=0
       base environment : C:\Users\runneradmin\miniconda3  (writable)
      conda av data dir : C:\Users\runneradmin\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/rdkit/win-64
                          https://conda.anaconda.org/rdkit/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\runneradmin\conda_pkgs_dir
       envs directories : C:\Users\runneradmin\miniconda3\envs
                          C:\Users\runneradmin\.conda\envs
                          C:\Users\runneradmin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Windows/10 Windows/10.0.20348 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
          administrator : True
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by skearnes**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hopefully a fix for #168

### CODE REVIEW

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Comment by skearnes** [comment]
@conda-forge-admin, please rerender

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
I wasn't able to directly test that this produces working environments since `build_locally.py` doesn't work for windows environments and I can't figure out how to install the artifacts that the CI builds create, so I think it's worth merging this and seeing if it helps. 
The windows builds aren't going to get more broken, right? :shrug:

**Comment by greglandrum** [comment]
I have tested the update builds with python 3.9, 3.10, and 3.12 by doing the following and everything looks good:
```
conda create -n py310_rdkit python=3.10 rdkit
conda activate py310_rdkit
python -c "from rdkit import Chem"
```
I was getting the problems with DLL loading before, but things are fine now.

Thanks @skearnes

**Comment by RMeli** [comment]
GitHub CI with this latest version seems to work as expected (see https://github.com/RMeli/spyrmsd/pull/136). Thank you!

**Pull request merged**
